// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGaDQW6SJlj-lEapkAIkjgoHtDwoonJ7Y',
    appId: '1:424341644593:web:43d20621480953a64cbc10',
    messagingSenderId: '424341644593',
    projectId: 'expensesnap-5f47c',
    authDomain: 'expensesnap-5f47c.firebaseapp.com',
    storageBucket: 'expensesnap-5f47c.firebasestorage.app',
    measurementId: 'G-9M5JW9GGGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6M6IDK_p7CtOYBJ0Z6jxjNIDBlUYt80w',
    appId: '1:424341644593:android:847caa7bbca617f44cbc10',
    messagingSenderId: '424341644593',
    projectId: 'expensesnap-5f47c',
    storageBucket: 'expensesnap-5f47c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEpH0Tv56mf7gjUjoIl_4okwQSiOAp_lc',
    appId: '1:424341644593:ios:934be8f8ef94c6354cbc10',
    messagingSenderId: '424341644593',
    projectId: 'expensesnap-5f47c',
    storageBucket: 'expensesnap-5f47c.firebasestorage.app',
    androidClientId:
        '424341644593-8u1spp8v4gkjdak55cmislssr9ov8tp8.apps.googleusercontent.com',
    iosClientId:
        '424341644593-nlrqehunda4q0ru577kbj8i9ahk8b7fi.apps.googleusercontent.com',
    iosBundleId: 'com.example.receiptApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEpH0Tv56mf7gjUjoIl_4okwQSiOAp_lc',
    appId: '1:424341644593:ios:934be8f8ef94c6354cbc10',
    messagingSenderId: '424341644593',
    projectId: 'expensesnap-5f47c',
    storageBucket: 'expensesnap-5f47c.firebasestorage.app',
    androidClientId:
        '424341644593-8u1spp8v4gkjdak55cmislssr9ov8tp8.apps.googleusercontent.com',
    iosClientId:
        '424341644593-nlrqehunda4q0ru577kbj8i9ahk8b7fi.apps.googleusercontent.com',
    iosBundleId: 'com.example.receiptApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGaDQW6SJlj-lEapkAIkjgoHtDwoonJ7Y',
    appId: '1:424341644593:web:bcafe20bc846fb404cbc10',
    messagingSenderId: '424341644593',
    projectId: 'expensesnap-5f47c',
    authDomain: 'expensesnap-5f47c.firebaseapp.com',
    storageBucket: 'expensesnap-5f47c.firebasestorage.app',
    measurementId: 'G-EKWSJC86JF',
  );
}
